[
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO AMAZONAS Carrera 11 No. 12-32 Barrio Victoria Regia, Comando Policía Amazonas",
   "DEPARTAMENTO": "AMAZONAS",
   "CIUDAD": "LETICIA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO AMAZONAS",
   "DIRECCION": "Carrera 11 No. 12-32 Barrio Victoria Regia, Comando Policía Amazonas"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO DISTRITO BELLO Avenida 43 No. 50-75",
   "DEPARTAMENTO": "ANTIOQUIA",
   "CIUDAD": "BELLO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO DISTRITO BELLO",
   "DIRECCION": "Avenida 43 No. 50-75"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA REGIONAL VALLE DE ABURRÁ Carrera 43A  No. 48C Sur 45",
   "DEPARTAMENTO": "ANTIOQUIA",
   "CIUDAD": "ENVIGADO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA REGIONAL VALLE DE ABURRÁ",
   "DIRECCION": "Carrera 43A  No. 48C Sur 45"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA CARLOS EUGENIO RESTREPO Vereda el Morrón",
   "DEPARTAMENTO": "ANTIOQUIA",
   "CIUDAD": "LA ESTRELLA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA CARLOS EUGENIO RESTREPO",
   "DIRECCION": "Vereda el Morrón"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO ANTIOQUIA Calle 71 No. 65-20",
   "DEPARTAMENTO": "ANTIOQUIA",
   "CIUDAD": "MEDELLÍN",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO ANTIOQUIA",
   "DIRECCION": "Calle 71 No. 65-20"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA DE SUBOFICIALES CARLOS HOLGUÍN Carrera 64 A No.113-17",
   "DEPARTAMENTO": "ANTIOQUIA",
   "CIUDAD": "MEDELLÍN",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA DE SUBOFICIALES CARLOS HOLGUÍN",
   "DIRECCION": "Carrera 64 A No.113-17"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO RIONEGRO Carrera 70 No. 44-25",
   "DEPARTAMENTO": "ANTIOQUIA",
   "CIUDAD": "RIONEGRO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO RIONEGRO",
   "DIRECCION": "Carrera 70 No. 44-25"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES URABÁ Kilómetro 5 vía Carepa- Apartadó-Vereda el Reposo, Base Departamento de Policía Urabá",
   "DEPARTAMENTO": "APARTADÓ",
   "CIUDAD": "URABÁ",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES URABÁ",
   "DIRECCION": "Kilómetro 5 vía Carepa- Apartadó-Vereda el Reposo, Base Departamento de Policía Urabá"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO ARAUCA Calle 15 No. 7 - 180 Via Puente Internacional Comando de Policia Arauca",
   "DEPARTAMENTO": "ARAUCA",
   "CIUDAD": "ARAUCA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO ARAUCA",
   "DIRECCION": "Calle 15 No. 7 - 180 Via Puente Internacional Comando de Policia Arauca"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES ARAUCA Calle 15 No. 7 - 180 Via Puente Internacional Comando de Policia Arauca",
   "DEPARTAMENTO": "ARAUCA",
   "CIUDAD": "ARAUCA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES ARAUCA",
   "DIRECCION": "Calle 15 No. 7 - 180 Via Puente Internacional Comando de Policia Arauca"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES QUINDÍO Carrera 13A No.1A - 117 Avenida Bolívar",
   "DEPARTAMENTO": "ARMENIA",
   "CIUDAD": "QUINDÍO",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES QUINDÍO",
   "DIRECCION": "Carrera 13A No.1A - 117 Avenida Bolívar"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA REGIONAL DEL CARIBE Avenida Circunvalar No. 45-124 Soledad",
   "DEPARTAMENTO": "ATLÁNTICO",
   "CIUDAD": "SOLEDAD",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA REGIONAL DEL CARIBE",
   "DIRECCION": "Avenida Circunvalar No. 45-124 Soledad"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA DE CHAPINERO Calle 67 No. 13-18",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA DE CHAPINERO",
   "DIRECCION": "Calle 67 No. 13-18"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA DE SAN ANTONIO Avenida Caracas No. 2-67 Sur",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA DE SAN ANTONIO",
   "DIRECCION": "Avenida Caracas No. 2-67 Sur"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA DEL NORTE Carrera 70 D No.116 - 12",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA DEL NORTE",
   "DIRECCION": "Carrera 70 D No.116 - 12"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA DEL SUR Calle 41 D No. 78 N- 05 Sur",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA DEL SUR",
   "DIRECCION": "Calle 41 D No. 78 N- 05 Sur"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA SEDE DE SEGURIDAD SOCIAL Calle 44 No.50-51 CAN Sede de Seguridad Social",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA SEDE DE SEGURIDAD SOCIAL",
   "DIRECCION": "Calle 44 No.50-51 CAN Sede de Seguridad Social"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI CAJA DE SUELDOS DE RETIRO Carrera 7 No. 13-58",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI CAJA DE SUELDOS DE RETIRO",
   "DIRECCION": "Carrera 7 No. 13-58"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI CASA DEL OFICIAL RETIRADO Carrera 19 No.118-63",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI CASA DEL OFICIAL RETIRADO",
   "DIRECCION": "Carrera 19 No.118-63"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COLEGIO SAN LUIS Avenida Boyacá No. 142 A 55",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COLEGIO SAN LUIS",
   "DIRECCION": "Avenida Boyacá No. 142 A 55"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI CENTRO DE ESTUDIOS SUPERIORES Avenida Boyacá No. 142 A 55",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI CENTRO DE ESTUDIOS SUPERIORES",
   "DIRECCION": "Avenida Boyacá No. 142 A 55"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO METROPOLITANA DE BOGOTÁ Carrera 15 No. 6-38",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO METROPOLITANA DE BOGOTÁ",
   "DIRECCION": "Carrera 15 No. 6-38"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA DE CADETES GENERAL SANTANDER Avenida 27 Sur No. 44-01 Muzú",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA DE CADETES GENERAL SANTANDER",
   "DIRECCION": "Avenida 27 Sur No. 44-01 Muzú"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESTACIÓN BOSA Calle 65 Sur No. 77 N 23",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESTACIÓN BOSA",
   "DIRECCION": "Calle 65 Sur No. 77 N 23"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESTACIÓN ENGATIVÁ Carrera 78 No. 70-58",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESTACIÓN ENGATIVÁ",
   "DIRECCION": "Carrera 78 No. 70-58"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESTACIÓN SAN CRISTÓBAL Avenida 1 de Mayo No. 1-40",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESTACIÓN SAN CRISTÓBAL",
   "DIRECCION": "Avenida 1 de Mayo No. 1-40"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESTACIÓN TRÁNSITO Calle 12 No. 35-82",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESTACIÓN TRÁNSITO",
   "DIRECCION": "Calle 12 No. 35-82"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESTACIÓN USME Avenida Usme No. 96 A-97 Sur",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESTACIÓN USME",
   "DIRECCION": "Avenida Usme No. 96 A-97 Sur"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI KENNEDY Carrera 78 k No. 5b-06  Barrio Mandalay",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI KENNEDY",
   "DIRECCION": "Carrera 78 k No. 5b-06  Barrio Mandalay"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI POLICÍA DE CARRETERAS Carrera 128 No. 17-15",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI POLICÍA DE CARRETERAS",
   "DIRECCION": "Carrera 128 No. 17-15"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI SERVICIO AÉREO Autopista Norte Entrada a Guaymaral Hangar 1",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI SERVICIO AÉREO",
   "DIRECCION": "Autopista Norte Entrada a Guaymaral Hangar 1"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI CENTRO AÉREO BOGOTÁ Avenida El Dorado Puerta No. 6 CATAM",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI CENTRO AÉREO BOGOTÁ",
   "DIRECCION": "Avenida El Dorado Puerta No. 6 CATAM"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA BG. EDGAR YESID DUARTE VALERO Carrera 68 b Bis No. 44-58 Edificio \nBG. Edgar Yesid Duarte Valero Torre B",
   "DEPARTAMENTO": "BOGOTÁ",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA BG. EDGAR YESID DUARTE VALERO",
   "DIRECCION": "Carrera 68 b Bis No. 44-58 Edificio \nBG. Edgar Yesid Duarte Valero Torre B"
 },
 {
   "NOMBRE HOMOLOGADO": "ÁREA GESTIÓN DE PRESTACIÓN SERVICIOS DE SALUD Calle 44 No.50-51 CAN Sede de Seguridad Social",
   "DEPARTAMENTO": "BOGOTÁ, D.C.",
   "CIUDAD": "APRES",
   "NOMBRE DEL ESP O PROGRAMA": "ÁREA GESTIÓN DE PRESTACIÓN SERVICIOS DE SALUD",
   "DIRECCION": "Calle 44 No.50-51 CAN Sede de Seguridad Social"
 },
 {
   "NOMBRE HOMOLOGADO": "ÁREA GESTIÓN DE PRESTACIÓN SERVICIOS DE SALUD Carrera 68 b Bis No. 44-58 Edificio BG. Edgar Yesid Duarte Valero Torre B",
   "DEPARTAMENTO": "BOGOTÁ, D.C.",
   "CIUDAD": "APRES",
   "NOMBRE DEL ESP O PROGRAMA": "ÁREA GESTIÓN DE PRESTACIÓN SERVICIOS DE SALUD",
   "DIRECCION": "Carrera 68 b Bis No. 44-58 Edificio BG. Edgar Yesid Duarte Valero Torre B"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES BOGOTÁ Carrera 68 b Bis No. 44-58 Edificio BG. Edgar Yesid Duarte Valero Torre A",
   "DEPARTAMENTO": "BOGOTÁ, D.C.",
   "CIUDAD": "BOGOTÁ",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES BOGOTÁ",
   "DIRECCION": "Carrera 68 b Bis No. 44-58 Edificio BG. Edgar Yesid Duarte Valero Torre A"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES BOGOTÁ Carrera 68 b Bis No. 44-58 Edificio BG. Edgar Yesid Duarte Valero Torre A",
   "DEPARTAMENTO": "BOGOTÁ, D.C.",
   "CIUDAD": "BOGOTÁ",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES BOGOTÁ",
   "DIRECCION": "Carrera 68 b Bis No. 44-58 Edificio BG. Edgar Yesid Duarte Valero Torre A"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA HOSPITAL EN CASA HOCEN Carrera 59 No. 26-21 CAN",
   "DEPARTAMENTO": "BOGOTÁ, D.C.",
   "CIUDAD": "HOCEN",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA HOSPITAL EN CASA HOCEN",
   "DIRECCION": "Carrera 59 No. 26-21 CAN"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA CARTAGENA DE INDIAS Calle Real No. 24-03 Barrio Manga Comando Policía Bolívar",
   "DEPARTAMENTO": "BOLÍVAR",
   "CIUDAD": "CARTAGENA DE INDIAS",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA CARTAGENA DE INDIAS",
   "DIRECCION": "Calle Real No. 24-03 Barrio Manga Comando Policía Bolívar"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI BOLÍVAR Manga Avenida de la Asamblea carrera 28 No. 21-227",
   "DEPARTAMENTO": "BOLÍVAR",
   "CIUDAD": "CARTAGENA DE INDIAS",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI BOLÍVAR",
   "DIRECCION": "Manga Avenida de la Asamblea carrera 28 No. 21-227"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO BARBOSA Carrera 9 No. 5c-30 Comando de Policía",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "BARBOSA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO BARBOSA",
   "DIRECCION": "Carrera 9 No. 5c-30 Comando de Policía"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO CHIQUINQUIRÁ Carrera 9 No. 14-60 Comando de Policía",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "CHIQUINQUIRÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO CHIQUINQUIRÁ",
   "DIRECCION": "Carrera 9 No. 14-60 Comando de Policía"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO DUITAMA Carrera 16 No. 10- 07  Comando de Policía",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "DUITAMA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO DUITAMA",
   "DIRECCION": "Carrera 16 No. 10- 07  Comando de Policía"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO GARAGOA Carrera 9 No. 13A-125  Comando de Policía",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "GARAGOA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO GARAGOA",
   "DIRECCION": "Carrera 9 No. 13A-125  Comando de Policía"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO MONIQUIRÁ Carrera 7 No. 20a-25 Comando de Policía",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "MONIQUIRÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO MONIQUIRÁ",
   "DIRECCION": "Carrera 7 No. 20a-25 Comando de Policía"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA RAFAEL REYES La Quinta Santa Rosa de Viterbo",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "SANTA ROSA DE VITERBO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA RAFAEL REYES",
   "DIRECCION": "La Quinta Santa Rosa de Viterbo"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO SOATÁ Carrera 6 No. 8-44 Comando",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "SOATÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO SOATÁ",
   "DIRECCION": "Carrera 6 No. 8-44 Comando"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO SOGAMOSO Carrera 14 con Calle 11 esquina Comando de Policía",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "SOGAMOSO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO SOGAMOSO",
   "DIRECCION": "Carrera 14 con Calle 11 esquina Comando de Policía"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA DE TUNJA Transversal 15 No. 16-01 Barrio Ricaurte",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "TUNJA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA DE TUNJA",
   "DIRECCION": "Transversal 15 No. 16-01 Barrio Ricaurte"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES BOYACÁ Carrera 4 No. 29-62 Comando La Remonta",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "TUNJA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES BOYACÁ",
   "DIRECCION": "Carrera 4 No. 29-62 Comando La Remonta"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA PROVINCIA DE VÉLEZ Vereda El Tun Tun finca Villa Elvia",
   "DEPARTAMENTO": "BOYACÁ",
   "CIUDAD": "VÉLEZ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA PROVINCIA DE VÉLEZ",
   "DIRECCION": "Vereda El Tun Tun finca Villa Elvia"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES SANTANDER Avenida 61 No. 10 - 200",
   "DEPARTAMENTO": "BUCARAMANGA",
   "CIUDAD": "SANTANDER",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES SANTANDER",
   "DIRECCION": "Avenida 61 No. 10 - 200"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES SANTANDER Avenida 61 No. 10 - 200",
   "DEPARTAMENTO": "BUCARAMANGA",
   "CIUDAD": "SANTANDER",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES SANTANDER",
   "DIRECCION": "Avenida 61 No. 10 - 200"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA DESAN Avenida 61 No. 10 - 200",
   "DEPARTAMENTO": "BUCARAMANGA",
   "CIUDAD": "SANTANDER",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA DESAN",
   "DIRECCION": "Avenida 61 No. 10 - 200"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI BUCARAMANGA Calle 48 No. 35 a -14 Barrio Cabecera del llano",
   "DEPARTAMENTO": "BUCARAMANGA",
   "CIUDAD": "SANTANDER",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI BUCARAMANGA",
   "DIRECCION": "Calle 48 No. 35 a -14 Barrio Cabecera del llano"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA DE LA TOSCANA Carrera 17 Calle 67 esquina, Avenida La Sultana",
   "DEPARTAMENTO": "CALDAS",
   "CIUDAD": "MANIZALES",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA DE LA TOSCANA",
   "DIRECCION": "Carrera 17 Calle 67 esquina, Avenida La Sultana"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA ALEJANDRO GUTIÉRREZ Calle 67 Carrera 17 esquina barrio La Toscana",
   "DEPARTAMENTO": "CALDAS",
   "CIUDAD": "MANIZALES",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA ALEJANDRO GUTIÉRREZ",
   "DIRECCION": "Calle 67 Carrera 17 esquina barrio La Toscana"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES VALLE DEL CAUCA Avenida 10 Norte No. 16 N - 21 Barrio Granada",
   "DEPARTAMENTO": "CALI",
   "CIUDAD": "VALLE DEL CAUCA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES VALLE DEL CAUCA",
   "DIRECCION": "Avenida 10 Norte No. 16 N - 21 Barrio Granada"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES VALLE Avenida 10 Norte No. 16 N - 21 Barrio Granada",
   "DEPARTAMENTO": "CALI",
   "CIUDAD": "VALLE DEL CAUCA",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES VALLE",
   "DIRECCION": "Avenida 10 Norte No. 16 N - 21 Barrio Granada"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI CAQUETÁ Carrera 11a No. 19-50 barrio La Inmaculada",
   "DEPARTAMENTO": "CAQUETÁ",
   "CIUDAD": "FLORENCIA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI CAQUETÁ",
   "DIRECCION": "Carrera 11a No. 19-50 barrio La Inmaculada"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES BOLIVAR Calle Real No. 24-03 Barrio Manga Comando Policía Bolívar",
   "DEPARTAMENTO": "CARTAGENA DE INDIAS",
   "CIUDAD": "BOLÍVAR",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES BOLIVAR",
   "DIRECCION": "Calle Real No. 24-03 Barrio Manga Comando Policía Bolívar"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES BOLÍVAR Calle Real No. 24-03 Barrio Manga Comando Policía Bolívar",
   "DEPARTAMENTO": "CARTAGENA DE INDIAS",
   "CIUDAD": "BOLÍVAR",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES BOLÍVAR",
   "DIRECCION": "Calle Real No. 24-03 Barrio Manga Comando Policía Bolívar"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO CASANARE Diagonal 15 No. 13B - 05 BarrioVencedores Comando de Policía Casanare",
   "DEPARTAMENTO": "CASANARE",
   "CIUDAD": "YOPAL",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO CASANARE",
   "DIRECCION": "Diagonal 15 No. 13B - 05 BarrioVencedores Comando de Policía Casanare"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI POPAYÁN Calle 32 N No. 12 - 50 Barrio Campo Bello",
   "DEPARTAMENTO": "CAUCA",
   "CIUDAD": "POPAYÁN",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI POPAYÁN",
   "DIRECCION": "Calle 32 N No. 12 - 50 Barrio Campo Bello"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI SANTANDER DE QUILICHAO Avenida Panamericana Carrera 13 Calle 11 esquina",
   "DEPARTAMENTO": "CAUCA",
   "CIUDAD": "SANTANDER DE QUILICHAO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI SANTANDER DE QUILICHAO",
   "DIRECCION": "Avenida Panamericana Carrera 13 Calle 11 esquina"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI VALLEDUPAR Calle 14 No 15-16 Barrio Alfonso López",
   "DEPARTAMENTO": "CESAR",
   "CIUDAD": "VALLEDUPAR",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI VALLEDUPAR",
   "DIRECCION": "Calle 14 No 15-16 Barrio Alfonso López"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI CENTRO DE INSTRUCCIÓN YUTO Kilómetro 25 Vía Quibdó - Yuto \nEscuela de Policia Miguel Angel Caicedo Mena.",
   "DEPARTAMENTO": "CHOCÓ",
   "CIUDAD": "ATRATO/YUTO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI CENTRO DE INSTRUCCIÓN YUTO",
   "DIRECCION": "Kilómetro 25 Vía Quibdó - Yuto \nEscuela de Policia Miguel Angel Caicedo Mena."
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI SAN PEDRO CLAVER Carrera 30 Avenida Aeropuerto El Caraño Antiguo Colegio PONAL Barrio Santo Domingo",
   "DEPARTAMENTO": "CHOCÓ",
   "CIUDAD": "QUIBDÓ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI SAN PEDRO CLAVER",
   "DIRECCION": "Carrera 30 Avenida Aeropuerto El Caraño Antiguo Colegio PONAL Barrio Santo Domingo"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO LORICA Carrera 17 No.2-17",
   "DEPARTAMENTO": "CÓRDOBA",
   "CIUDAD": "LORICA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO LORICA",
   "DIRECCION": "Carrera 17 No.2-17"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI MONTERÍA Carrera 14 No. 41 - 61",
   "DEPARTAMENTO": "CÓRDOBA",
   "CIUDAD": "MONTERÍA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI MONTERÍA",
   "DIRECCION": "Carrera 14 No. 41 - 61"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO SAHAGÚN Carrera 11 No. 17-12 Barrio Playa Rica",
   "DEPARTAMENTO": "CÓRDOBA",
   "CIUDAD": "SAHAGÚN",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO SAHAGÚN",
   "DIRECCION": "Carrera 11 No. 17-12 Barrio Playa Rica"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO CUNDINAMARCA Carrera 58 No. 10-75 Comando de Policía Cundinamarca",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO CUNDINAMARCA",
   "DIRECCION": "Carrera 58 No. 10-75 Comando de Policía Cundinamarca"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES CUNDINAMARCA Carrera 68 b Bis No. 44-58 Edificio BG. Edgar Yesid Duarte Valero Torre A - Calle 13 No. 65-58 Puente Aranda Primer Piso",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES CUNDINAMARCA",
   "DIRECCION": "Carrera 68 b Bis No. 44-58 Edificio BG. Edgar Yesid Duarte Valero Torre A - Calle 13 No. 65-58 Puente Aranda Primer Piso"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO CÁQUEZA Carrera 4 Calle 4",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "CÁQUEZA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO CÁQUEZA",
   "DIRECCION": "Carrera 4 Calle 4"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO CHÍA Carrera 12 No. 16-05 Chía Centro",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "CHÍA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO CHÍA",
   "DIRECCION": "Carrera 12 No. 16-05 Chía Centro"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO FACATATIVÁ Calle 8 No 2 - 29 Bario Centro Facatativá",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "FACATATIVÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO FACATATIVÁ",
   "DIRECCION": "Calle 8 No 2 - 29 Bario Centro Facatativá"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA NACIONAL DE CARABINEROS Kilómetro 4 Vía Ecopetrol Hacienda las Margaritas",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "FACATATIVÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA NACIONAL DE CARABINEROS",
   "DIRECCION": "Kilómetro 4 Vía Ecopetrol Hacienda las Margaritas"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO FUSAGASUGÁ Calle 5 No. 6-49",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "FUSAGASUGÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO FUSAGASUGÁ",
   "DIRECCION": "Calle 5 No. 6-49"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA PROVINCIA DEL SUMAPAZ Calle 19 No. 50-24 Barrio Gran Colombia",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "FUSAGASUGÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA PROVINCIA DEL SUMAPAZ",
   "DIRECCION": "Calle 19 No. 50-24 Barrio Gran Colombia"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO GIRARDOT Calle No. 22 1-57",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "GIRARDOT",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO GIRARDOT",
   "DIRECCION": "Calle No. 22 1-57"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA GONZALO JIMENEZ DE QUESADA Kilómetro 20 Sibaté",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "SIBATÉ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA GONZALO JIMENEZ DE QUESADA",
   "DIRECCION": "Kilómetro 20 Sibaté"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI SOACHA Carrera 6 No.14-64 Centro",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "SOACHA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI SOACHA",
   "DIRECCION": "Carrera 6 No.14-64 Centro"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO VILLETA Carrera 7 Calle 4 esquina",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "VILLETA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO VILLETA",
   "DIRECCION": "Carrera 7 Calle 4 esquina"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO ZIPAQUIRÁ Avenida 15 No. 4A-60 Barrio Algarra III",
   "DEPARTAMENTO": "CUNDINAMARCA",
   "CIUDAD": "ZIPAQUIRÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO ZIPAQUIRÁ",
   "DIRECCION": "Avenida 15 No. 4A-60 Barrio Algarra III"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES ANTIOQUIA Carrera 43A No. 48C Sur 45",
   "DEPARTAMENTO": "ENVIGADO",
   "CIUDAD": "ANTIOQUIA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES ANTIOQUIA",
   "DIRECCION": "Carrera 43A No. 48C Sur 45"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA HOSPITAL EN CASA UPRES ANTIOQUIA Carrera 43A No. 48C Sur 45",
   "DEPARTAMENTO": "ENVIGADO",
   "CIUDAD": "ANTIOQUIA",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA HOSPITAL EN CASA UPRES ANTIOQUIA",
   "DIRECCION": "Carrera 43A No. 48C Sur 45"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES ANTIOQUIA Carrera 43A No. 48C Sur 45",
   "DEPARTAMENTO": "ENVIGADO",
   "CIUDAD": "ANTIOQUIA",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES ANTIOQUIA",
   "DIRECCION": "Carrera 43A No. 48C Sur 45"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA DEANT Carrera 43A No. 48C Sur 45",
   "DEPARTAMENTO": "ENVIGADO",
   "CIUDAD": "ANTIOQUIA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA DEANT",
   "DIRECCION": "Carrera 43A No. 48C Sur 45"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA NACIONAL DE OPERACIONES Vereda La Laguna vía Espinal",
   "DEPARTAMENTO": "ESPINAL",
   "CIUDAD": "TOLIMA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA NACIONAL DE OPERACIONES",
   "DIRECCION": "Vereda La Laguna vía Espinal"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES CAQUETÁ Carrera 11a No. 19-50 barrio La Inmaculada",
   "DEPARTAMENTO": "FLORENCIA",
   "CIUDAD": "CAQUETÁ",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES CAQUETÁ",
   "DIRECCION": "Carrera 11a No. 19-50 barrio La Inmaculada"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO GUAINÍA Carrera 5 No. 14-84 Avenida Simón Bolívar Comando de Policía Guainía",
   "DEPARTAMENTO": "GUAINÍA",
   "CIUDAD": "INÍRIDA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO GUAINÍA",
   "DIRECCION": "Carrera 5 No. 14-84 Avenida Simón Bolívar Comando de Policía Guainía"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO MAICAO Carrera 15 Calle 18 Centro",
   "DEPARTAMENTO": "GUAJIRA",
   "CIUDAD": "MAICAO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO MAICAO",
   "DIRECCION": "Carrera 15 Calle 18 Centro"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO GUAJIRA Carrera 15 Calle 7 esquina Barrio Camilo Torres",
   "DEPARTAMENTO": "GUAJIRA",
   "CIUDAD": "RIOHACHA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO GUAJIRA",
   "DIRECCION": "Carrera 15 Calle 7 esquina Barrio Camilo Torres"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO GUAVIARE Calle 9 No. 21-20 Barrio La Esperanza",
   "DEPARTAMENTO": "GUAVIARE",
   "CIUDAD": "SAN JOSÉ DEL GUAVIARE",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO GUAVIARE",
   "DIRECCION": "Calle 9 No. 21-20 Barrio La Esperanza"
 },
 {
   "NOMBRE HOMOLOGADO": "HOSPITAL CENTRAL Carrera 59 No. 26-21 CAN",
   "DEPARTAMENTO": "HOCEN",
   "CIUDAD": "BOGOTÁ, D.C.",
   "NOMBRE DEL ESP O PROGRAMA": "HOSPITAL CENTRAL",
   "DIRECCION": "Carrera 59 No. 26-21 CAN"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI GARZÓN Calle 3A No. 4 - 52 GARZÓN",
   "DEPARTAMENTO": "HUILA",
   "CIUDAD": "GARZÓN",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI GARZÓN",
   "DIRECCION": "Calle 3A No. 4 - 52 GARZÓN"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI LA PLATA Calle 8 No. 5-64 Barrio La Cordialidad",
   "DEPARTAMENTO": "HUILA",
   "CIUDAD": "LA PLATA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI LA PLATA",
   "DIRECCION": "Calle 8 No. 5-64 Barrio La Cordialidad"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA HUILA Carrera 22 sur No. 8b-15",
   "DEPARTAMENTO": "HUILA",
   "CIUDAD": "NEIVA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA HUILA",
   "DIRECCION": "Carrera 22 sur No. 8b-15"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI PITALITO Calle 19 a No. 2-05",
   "DEPARTAMENTO": "HUILA",
   "CIUDAD": "PITALITO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI PITALITO",
   "DIRECCION": "Calle 19 a No. 2-05"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES TOLIMA Carrera 14 Calle 4 esquina",
   "DEPARTAMENTO": "IBAGUÉ",
   "CIUDAD": "TOLIMA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES TOLIMA",
   "DIRECCION": "Carrera 14 Calle 4 esquina"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES TOLIMA Carrera 14 Calle 4 esquina",
   "DEPARTAMENTO": "IBAGUÉ",
   "CIUDAD": "TOLIMA",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES TOLIMA",
   "DIRECCION": "Carrera 14 Calle 4 esquina"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES GUAINIA Carrera 5 No. 14-84 Avenida Simón Bolívar Comando de Policía Guainía",
   "DEPARTAMENTO": "INÍRIDA",
   "CIUDAD": "GUAINÍA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES GUAINIA",
   "DIRECCION": "Carrera 5 No. 14-84 Avenida Simón Bolívar Comando de Policía Guainía"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES AMAZONAS Calle 14 No. 10-32 Barrio Victoria Regia, Comando Policía Amazonas",
   "DEPARTAMENTO": "LETICIA",
   "CIUDAD": "AMAZONAS",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES AMAZONAS",
   "DIRECCION": "Calle 14 No. 10-32 Barrio Victoria Regia, Comando Policía Amazonas"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI NUESTRA SEÑORA DEL ROSARIO Calle 22 No. 1C- 74 Barrio Centro",
   "DEPARTAMENTO": "MAGDALENA",
   "CIUDAD": "SANTA MARTA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI NUESTRA SEÑORA DEL ROSARIO",
   "DIRECCION": "Calle 22 No. 1C- 74 Barrio Centro"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA DE SANTA MARTA Calle 14 # 25 – 99",
   "DEPARTAMENTO": "MAGDALENA",
   "CIUDAD": "SANTA MARTA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA DE SANTA MARTA",
   "DIRECCION": "Calle 14 # 25 – 99"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES CALDAS Carrera 17 Calle 67 esquina, Avenida La Sultana",
   "DEPARTAMENTO": "MANIZALES",
   "CIUDAD": "CALDAS",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES CALDAS",
   "DIRECCION": "Carrera 17 Calle 67 esquina, Avenida La Sultana"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA DECAL Carrera 17 Calle 67 esquina, Avenida La Sultana",
   "DEPARTAMENTO": "MANIZALES",
   "CIUDAD": "CALDAS",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA DECAL",
   "DIRECCION": "Carrera 17 Calle 67 esquina, Avenida La Sultana"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES CALDAS Carrera 17 Calle 67 esquina, Avenida La Sultana",
   "DEPARTAMENTO": "MANIZALES",
   "CIUDAD": "CALDAS",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES CALDAS",
   "DIRECCION": "Carrera 17 Calle 67 esquina, Avenida La Sultana"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES META Carrera 47 A No. 30 - 08 Barrio Caudal",
   "DEPARTAMENTO": "META",
   "CIUDAD": "VILLAVICENCIO",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES META",
   "DIRECCION": "Carrera 47 A No. 30 - 08 Barrio Caudal"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA EDUARDO CUEVAS Calle 44 No. 35-16 Barrio El Triunfo",
   "DEPARTAMENTO": "META",
   "CIUDAD": "VILLAVICENCIO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA EDUARDO CUEVAS",
   "DIRECCION": "Calle 44 No. 35-16 Barrio El Triunfo"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES VAUPES Carrera 13 A No. 15 A-75 Barrio Centro Mitú",
   "DEPARTAMENTO": "MITÚ",
   "CIUDAD": "VAUPÉS",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES VAUPES",
   "DIRECCION": "Carrera 13 A No. 15 A-75 Barrio Centro Mitú"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES PUTUMAYO Calle 8 Carrera 9 Esquina",
   "DEPARTAMENTO": "MOCOA",
   "CIUDAD": "PUTUMAYO",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES PUTUMAYO",
   "DIRECCION": "Calle 8 Carrera 9 Esquina"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES CÓRDOBA Carrera 14 No. 41 - 61",
   "DEPARTAMENTO": "MONTERÍA",
   "CIUDAD": "CÓRDOBA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES CÓRDOBA",
   "DIRECCION": "Carrera 14 No. 41 - 61"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO IPIALES Carrera 13 No. 25 C – 15 Barrio Miramar",
   "DEPARTAMENTO": "NARIÑO",
   "CIUDAD": "IPIALES",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO IPIALES",
   "DIRECCION": "Carrera 13 No. 25 C – 15 Barrio Miramar"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI PALERMO Carrera 35 No. 19 - 119 Barrio Palermo",
   "DEPARTAMENTO": "NARIÑO",
   "CIUDAD": "PASTO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI PALERMO",
   "DIRECCION": "Carrera 35 No. 19 - 119 Barrio Palermo"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO TUMACO Calle 8 No 10 - 15 Avenida Ferrocarril",
   "DEPARTAMENTO": "NARIÑO",
   "CIUDAD": "SAN ANDRÉS DE TUMACO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO TUMACO",
   "DIRECCION": "Calle 8 No 10 - 15 Avenida Ferrocarril"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES HUILA Carrera 22 sur No. 8b-15",
   "DEPARTAMENTO": "NEIVA",
   "CIUDAD": "HUILA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES HUILA",
   "DIRECCION": "Carrera 22 sur No. 8b-15"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES HUILA Carrera 22 sur No. 8b-15",
   "DEPARTAMENTO": "NEIVA",
   "CIUDAD": "HUILA",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES HUILA",
   "DIRECCION": "Carrera 22 sur No. 8b-15"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA DEUIL Carrera 22 sur No. 26a-21 Barrio Fronteras del Milenio",
   "DEPARTAMENTO": "NEIVA",
   "CIUDAD": "HUILA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA DEUIL",
   "DIRECCION": "Carrera 22 sur No. 26a-21 Barrio Fronteras del Milenio"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO PAMPLONA Carrera 9 No. 13 - 151 Barrio el Camellón",
   "DEPARTAMENTO": "NORTE DE SANTANDER",
   "CIUDAD": "PAMPLONA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO PAMPLONA",
   "DIRECCION": "Carrera 9 No. 13 - 151 Barrio el Camellón"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA CÚCUTA Calle 22 N No. 2-03 Urbanización Tasajero",
   "DEPARTAMENTO": "NORTE DE SANTANDER",
   "CIUDAD": "SAN JOSÉ DE CÚCUTA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA CÚCUTA",
   "DIRECCION": "Calle 22 N No. 2-03 Urbanización Tasajero"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES NARIÑO Carrera 35 No. 19 - 119 Barrio Palermo",
   "DEPARTAMENTO": "PASTO",
   "CIUDAD": "NARIÑO",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES NARIÑO",
   "DIRECCION": "Carrera 35 No. 19 - 119 Barrio Palermo"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES NARIÑO Carrera 35 No. 19 - 119 Barrio Palermo",
   "DEPARTAMENTO": "PASTO",
   "CIUDAD": "NARIÑO",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES NARIÑO",
   "DIRECCION": "Carrera 35 No. 19 - 119 Barrio Palermo"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES RISARALDA Calle 94 Avenida Villa Olímpica",
   "DEPARTAMENTO": "PEREIRA",
   "CIUDAD": "RISARALDA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES RISARALDA",
   "DIRECCION": "Calle 94 Avenida Villa Olímpica"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES RISARALDA Calle 94 Avenida Villa Olímpica",
   "DEPARTAMENTO": "PEREIRA",
   "CIUDAD": "RISARALDA",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES RISARALDA",
   "DIRECCION": "Calle 94 Avenida Villa Olímpica"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES CAUCA Calle 32 N No. 12 - 50 Barrio Campo Bello",
   "DEPARTAMENTO": "POPAYÁN",
   "CIUDAD": "CAUCA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES CAUCA",
   "DIRECCION": "Calle 32 N No. 12 - 50 Barrio Campo Bello"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES VICHADA Carrera 9 No. 18-55 B Centro Puerto Carreño",
   "DEPARTAMENTO": "PUERTO CARREÑO",
   "CIUDAD": "VICHADA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES VICHADA",
   "DIRECCION": "Carrera 9 No. 18-55 B Centro Puerto Carreño"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO PUTUMAYO Calle 8 Carrera 9 Esquina",
   "DEPARTAMENTO": "PUTUMAYO",
   "CIUDAD": "MOCOA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO PUTUMAYO",
   "DIRECCION": "Calle 8 Carrera 9 Esquina"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES CHOCÓ Carrera 30 Avenida Aeropuerto El Caraño Antiguo Colegio PONAL Barrio Santo Domingo",
   "DEPARTAMENTO": "QUIBDÓ",
   "CIUDAD": "CHOCÓ",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES CHOCÓ",
   "DIRECCION": "Carrera 30 Avenida Aeropuerto El Caraño Antiguo Colegio PONAL Barrio Santo Domingo"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ARMENIA Carrera 13A No.1A - 117 Avenida Bolívar",
   "DEPARTAMENTO": "QUINDÍO",
   "CIUDAD": "ARMENIA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ARMENIA",
   "DIRECCION": "Carrera 13A No.1A - 117 Avenida Bolívar"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO CALARCÁ Calle 42 No. 19-07 Esquina Barrio Cacique Comando Policía Calarcá",
   "DEPARTAMENTO": "QUINDÍO",
   "CIUDAD": "CALARCÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO CALARCÁ",
   "DIRECCION": "Calle 42 No. 19-07 Esquina Barrio Cacique Comando Policía Calarcá"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI SEVILLA Carrera 50 No. 53-29 Barrio el Carmen",
   "DEPARTAMENTO": "QUINDÍO",
   "CIUDAD": "SEVILLA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI SEVILLA",
   "DIRECCION": "Carrera 50 No. 53-29 Barrio el Carmen"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES GUAJIRA Carrera 15 Calle 7 esquina Barrio Camilo Torres",
   "DEPARTAMENTO": "RIOHACHA",
   "CIUDAD": "GUAJIRA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES GUAJIRA",
   "DIRECCION": "Carrera 15 Calle 7 esquina Barrio Camilo Torres"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI CARTAGO Calle 13 No. 3N-91 Barrio Prado (Cartago)",
   "DEPARTAMENTO": "RISARALDA",
   "CIUDAD": "CARTAGO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI CARTAGO",
   "DIRECCION": "Calle 13 No. 3N-91 Barrio Prado (Cartago)"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI UNIDAD MÉDICA RISARALDA Calle 94 Avenida Villa Olímpica",
   "DEPARTAMENTO": "RISARALDA",
   "CIUDAD": "PEREIRA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI UNIDAD MÉDICA RISARALDA",
   "DIRECCION": "Calle 94 Avenida Villa Olímpica"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA Carrera 2 # 7-141 Barrio Obrero (Primer Piso de la Clínica Villa Real)",
   "DEPARTAMENTO": "SAN ANDRÉS",
   "CIUDAD": "SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA",
   "DIRECCION": "Carrera 2 # 7-141 Barrio Obrero (Primer Piso de la Clínica Villa Real)"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI SAN ANDRÉS Y PROVIDENCIA Carrera 2 # 7-141 Barrio Obrero (Primer Piso de la Clínica Villa Real)",
   "DEPARTAMENTO": "SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA",
   "CIUDAD": "SAN ANDRÉS",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI SAN ANDRÉS Y PROVIDENCIA",
   "DIRECCION": "Carrera 2 # 7-141 Barrio Obrero (Primer Piso de la Clínica Villa Real)"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES NORTE DE SANTANDER Calle 22 N No. 2-03 Urbanización Tasajero",
   "DEPARTAMENTO": "SAN JOSÉ DE CÚCUTA",
   "CIUDAD": "NORTE DE SANTANDER",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES NORTE DE SANTANDER",
   "DIRECCION": "Calle 22 N No. 2-03 Urbanización Tasajero"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES NORTE DE SANTANDER Calle 22 N No. 2-03 Urbanización Tasajero",
   "DEPARTAMENTO": "SAN JOSÉ DE CÚCUTA",
   "CIUDAD": "NORTE DE SANTANDER",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES NORTE DE SANTANDER",
   "DIRECCION": "Calle 22 N No. 2-03 Urbanización Tasajero"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES GUAVIARE Calle 9 No. 21-65",
   "DEPARTAMENTO": "SAN JOSÉ DEL GUAVIARE",
   "CIUDAD": "GUAVIARE",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES GUAVIARE",
   "DIRECCION": "Calle 9 No. 21-65"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES MAGDALENA Calle 22 No. 1C- 74 Barrio Centro",
   "DEPARTAMENTO": "SANTA MARTA",
   "CIUDAD": "MAGDALENA",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES MAGDALENA",
   "DIRECCION": "Calle 22 No. 1C- 74 Barrio Centro"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO AGUACHICA Calle 6a No 18-08",
   "DEPARTAMENTO": "SANTANDER",
   "CIUDAD": "AGUACHICA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO AGUACHICA",
   "DIRECCION": "Calle 6a No 18-08"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO MAGDALENA MEDIO Carrera 24 No. 46-32 Barrio el Recreo",
   "DEPARTAMENTO": "SANTANDER",
   "CIUDAD": "BARRANCABERMEJA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO MAGDALENA MEDIO",
   "DIRECCION": "Carrera 24 No. 46-32 Barrio el Recreo"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA REGIONAL DEL ORIENTE Avenida 61 No. 10 - 200",
   "DEPARTAMENTO": "SANTANDER",
   "CIUDAD": "BUCARAMANGA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA REGIONAL DEL ORIENTE",
   "DIRECCION": "Avenida 61 No. 10 - 200"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO MÁLAGA Calle 14 No. 11-84 Barrio Ricaurte Comando de Policía",
   "DEPARTAMENTO": "SANTANDER",
   "CIUDAD": "MÁLAGA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO MÁLAGA",
   "DIRECCION": "Calle 14 No. 11-84 Barrio Ricaurte Comando de Policía"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI SAN GIL Carrera 8 No. 13-36",
   "DEPARTAMENTO": "SANTANDER",
   "CIUDAD": "SAN GIL",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI SAN GIL",
   "DIRECCION": "Carrera 8 No. 13-36"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI SOCORRO Carrera 14 No. 10-76",
   "DEPARTAMENTO": "SANTANDER",
   "CIUDAD": "SOCORRO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI SOCORRO",
   "DIRECCION": "Carrera 14 No. 10-76"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES SUCRE Calle 26 No. 16A-24 Barrio Sabanas de Nariño",
   "DEPARTAMENTO": "SINCELEJO",
   "CIUDAD": "SUCRE",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES SUCRE",
   "DIRECCION": "Calle 26 No. 16A-24 Barrio Sabanas de Nariño"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES ATLÁNTICO Avenida Circunvalar No. 45-124 Soledad",
   "DEPARTAMENTO": "SOLEDAD",
   "CIUDAD": "ATLÁNTICO",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES ATLÁNTICO",
   "DIRECCION": "Avenida Circunvalar No. 45-124 Soledad"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES ATLÁNTICO Avenida Circunvalar No. 45-124 Soledad",
   "DEPARTAMENTO": "SOLEDAD",
   "CIUDAD": "ATLÁNTICO",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES ATLÁNTICO",
   "DIRECCION": "Avenida Circunvalar No. 45-124 Soledad"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA DEATA Avenida Circunvalar No. 45-124 Soledad",
   "DEPARTAMENTO": "SOLEDAD",
   "CIUDAD": "ATLÁNTICO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA DEATA",
   "DIRECCION": "Avenida Circunvalar No. 45-124 Soledad"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA RAFAEL NÚÑEZ Carretera Troncal de Occidente Kilómetro 5 Corozal",
   "DEPARTAMENTO": "SUCRE",
   "CIUDAD": "COROZAL",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA RAFAEL NÚÑEZ",
   "DIRECCION": "Carretera Troncal de Occidente Kilómetro 5 Corozal"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO SUCRE Calle 26 No. 16A-24 Barrio Sabanas de Nariño",
   "DEPARTAMENTO": "SUCRE",
   "CIUDAD": "SINCELEJO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO SUCRE",
   "DIRECCION": "Calle 26 No. 16A-24 Barrio Sabanas de Nariño"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA GABRIEL GONZÁLEZ Carrera 12 Calle 6",
   "DEPARTAMENTO": "TOLIMA",
   "CIUDAD": "ESPINAL",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA GABRIEL GONZÁLEZ",
   "DIRECCION": "Carrera 12 Calle 6"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI IBAGUÉ Carrera 14 Calle 4 esquina",
   "DEPARTAMENTO": "TOLIMA",
   "CIUDAD": "IBAGUÉ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI IBAGUÉ",
   "DIRECCION": "Carrera 14 Calle 4 esquina"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI DISTRITO LA DORADA Calle 12 No. 7-05/09 Barrio Centro",
   "DEPARTAMENTO": "TOLIMA",
   "CIUDAD": "LA DORADA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI DISTRITO LA DORADA",
   "DIRECCION": "Calle 12 No. 7-05/09 Barrio Centro"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ESCUELA DE AVIACIÓN Escuela de Aviación Policia Nacional",
   "DEPARTAMENTO": "TOLIMA",
   "CIUDAD": "SAN SEBASTIÁN DE MARIQUITA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ESCUELA DE AVIACIÓN",
   "DIRECCION": "Escuela de Aviación Policia Nacional"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA DEBOY Transversal 15 No. 16-01 Barrio Ricaurte",
   "DEPARTAMENTO": "TUNJA",
   "CIUDAD": "BOYACÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA DEBOY",
   "DIRECCION": "Transversal 15 No. 16-01 Barrio Ricaurte"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO URABÁ Kilómetro 5 vía Carepa- Apartadó-Vereda el Reposo, Base Departamento de Policía Urabá",
   "DEPARTAMENTO": "URABÁ",
   "CIUDAD": "APARTADÓ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO URABÁ",
   "DIRECCION": "Kilómetro 5 vía Carepa- Apartadó-Vereda el Reposo, Base Departamento de Policía Urabá"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI BUENAVENTURA Avenida 6 No. 50 - 110 Barrio El Galeón",
   "DEPARTAMENTO": "VALLE DEL CAUCA",
   "CIUDAD": "BUENAVENTURA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI BUENAVENTURA",
   "DIRECCION": "Avenida 6 No. 50 - 110 Barrio El Galeón"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPCO CLÍNICA DEVAL Calle 48 No. 86-08 Esquina Barrio El Caney",
   "DEPARTAMENTO": "VALLE DEL CAUCA",
   "CIUDAD": "CALI",
   "NOMBRE DEL ESP O PROGRAMA": "ESPCO CLÍNICA DEVAL",
   "DIRECCION": "Calle 48 No. 86-08 Esquina Barrio El Caney"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI NUESTRA SEÑORA DE FÁTIMA Avenida 10 Norte No. 16 N - 21 Barrio Granada",
   "DEPARTAMENTO": "VALLE DEL CAUCA",
   "CIUDAD": "CALI",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI NUESTRA SEÑORA DE FÁTIMA",
   "DIRECCION": "Avenida 10 Norte No. 16 N - 21 Barrio Granada"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI BUGA Carrera 16 No. 7-68 Barrio José María Cabal",
   "DEPARTAMENTO": "VALLE DEL CAUCA",
   "CIUDAD": "GUADALAJARA DE BUGA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI BUGA",
   "DIRECCION": "Carrera 16 No. 7-68 Barrio José María Cabal"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI PALMIRA Carrera  31 No. 21-52 Barrio Nueva Palmira",
   "DEPARTAMENTO": "VALLE DEL CAUCA",
   "CIUDAD": "PALMIRA",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI PALMIRA",
   "DIRECCION": "Carrera  31 No. 21-52 Barrio Nueva Palmira"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI ROLDANILLO Calle 8 # 5–51",
   "DEPARTAMENTO": "VALLE DEL CAUCA",
   "CIUDAD": "ROLDANILLO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI ROLDANILLO",
   "DIRECCION": "Calle 8 # 5–51"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI TULUÁ Carrera 44 # 37-164",
   "DEPARTAMENTO": "VALLE DEL CAUCA",
   "CIUDAD": "TULUÁ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI TULUÁ",
   "DIRECCION": "Carrera 44 # 37-164"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES CESAR Calle 14 No 15-16 Barrio Alfonso López",
   "DEPARTAMENTO": "VALLEDUPAR",
   "CIUDAD": "CESAR",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES CESAR",
   "DIRECCION": "Calle 14 No 15-16 Barrio Alfonso López"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO VAUPÉS Carrera 13 A No. 15 A-75 Barrio Centro  Mitú",
   "DEPARTAMENTO": "VAUPÉS",
   "CIUDAD": "MITÚ",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO VAUPÉS",
   "DIRECCION": "Carrera 13 A No. 15 A-75 Barrio Centro  Mitú"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI COMANDO VICHADA Carrera 9 No. 18-55 B Centro Puerto Carreño",
   "DEPARTAMENTO": "VICHADA",
   "CIUDAD": "PUERTO CARREÑO",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI COMANDO VICHADA",
   "DIRECCION": "Carrera 9 No. 18-55 B Centro Puerto Carreño"
 },
 {
   "NOMBRE HOMOLOGADO": "PROGRAMA MÉDICO DOMICILIARIO UPRES META Calle 44 No. 35-96 Barrio El Triunfo",
   "DEPARTAMENTO": "VILLAVICENCIO",
   "CIUDAD": "META",
   "NOMBRE DEL ESP O PROGRAMA": "PROGRAMA MÉDICO DOMICILIARIO UPRES META",
   "DIRECCION": "Calle 44 No. 35-96 Barrio El Triunfo"
 },
 {
   "NOMBRE HOMOLOGADO": "ESPRI NUESTRA SEÑORA DEL PILAR Calle 44 No. 35-96 Barrio El Triunfo",
   "DEPARTAMENTO": "VILLAVICENCIO",
   "CIUDAD": "META",
   "NOMBRE DEL ESP O PROGRAMA": "ESPRI NUESTRA SEÑORA DEL PILAR",
   "DIRECCION": "Calle 44 No. 35-96 Barrio El Triunfo"
 },
 {
   "NOMBRE HOMOLOGADO": "UPRES CASANARE Diagonal 15 No. 13B - 05 BarrioVencedores Comando de Policía Casanare",
   "DEPARTAMENTO": "YOPAL",
   "CIUDAD": "CASANARE",
   "NOMBRE DEL ESP O PROGRAMA": "UPRES CASANARE",
   "DIRECCION": "Diagonal 15 No. 13B - 05 BarrioVencedores Comando de Policía Casanare"
 }
]
